## crear usuario
POST http://localhost:3001/api/auth/new 
Content-Type: application/json

{
    "name": "Renzo",
    "email": "renzo@google.com",
    "password": "123456"
}


## login usuario

POST http://localhost:3001/api/auth/ 

## Renovar token 

GET http://localhost:3001/api/auth/renew 
